"""initial schema

Revision ID: 67a95768e220
Revises: 
Create Date: 2026-08-12 22:04:42.901025
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # autogenerate emits bare Text() in the JSONB variant
from sqlalchemy.dialects import postgresql

revision: str = '67a95768e220'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=120), nullable=False),
    sa.Column('is_new_beneficiary', sa.Boolean(), nullable=False),
    sa.Column('customer_msisdn', sa.String(length=24), nullable=False),
    sa.Column('signal_msisdn', sa.String(length=24), nullable=False),
    sa.Column('customer_locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('approve', 'intervene', 'decline', name='decisionoutcome', native_enum=False, length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('reasoning_trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('total_latency_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('signal_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('api_name', sa.String(length=64), nullable=False),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('response_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.Enum('live', 'fallback', name='signalsourcekind', native_enum=False, length=16), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_calls_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('voice_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ringing', 'in_progress', 'completed', 'failed', name='voicestatus', native_enum=False, length=16), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed_legitimate', 'scam_detected', 'no_answer', 'inconclusive', name='voiceoutcome', native_enum=False, length=24), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_calls_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_calls_transaction_id'))

    op.drop_table('voice_calls')
    with op.batch_alter_table('signal_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_calls_transaction_id'))

    op.drop_table('signal_calls')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_transaction_id'))

    op.drop_table('decisions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
