"""voice call channel

Records whether the customer was reached by phone or in the browser. A UAE mobile
cannot be reached by any AI voice platform, because Etisalat and du are required to
block VoIP-originated termination, so the web channel carries the same conversation
with no carrier in the path. The two are not the same thing and the dashboard should
not imply otherwise.

Revision ID: 73f408e50884
Revises: 67a95768e220
Create Date: 2026-08-31 20:11:56.437935
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '73f408e50884'
down_revision: str | None = '67a95768e220'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default is not optional here. The column is NOT NULL, and every call
    # recorded before this migration is a phone call, so without a default the upgrade
    # fails on any database that has already handled a transaction. Autogenerate does
    # not know that; it left the column bare.
    with op.batch_alter_table('voice_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'channel',
            sa.Enum('phone', 'web', name='voicechannel', native_enum=False,
                    create_constraint=True, length=8),
            nullable=False,
            server_default='phone',
        ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_calls', schema=None) as batch_op:
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
